### ISSUE TITLE
Request for an apk android app for testing

### ISSUE THREAD

**Issue by haicoi311** [nerv55/opensourcepos#6]
hi @nerv55 , As mentioned in another post in the main source. I Would like to have an apk app in order to test the function. 
I can you tell me how can I let your app connect with my own database?

**Comment by nerv55** [comment]
Give the url to compile version for your site.

**Comment by haicoi311** [comment]
My site is running on the ospos 3.2.0. Is this ok or I have to turn to the newest version: 3.2.3?

**Comment by nerv55** [comment]
Here url for you to donwload, the apk file https://wetransfer.com/downloads/fc091a7527b1f25b83be5e3406763afa20181204143549/255483c72d07ee2c25f0f63269675ff720181204143549/d019e8

**Comment by nerv55** [comment]
for test you can log in with "demo1" password  "12345678"
