### ISSUE TITLE
Custom report

### ISSUE THREAD

**Issue by data2base** [nerv55/opensourcepos#7]
Thanks, as requested. 
:)

[databas1_ospo13.zip](https://github.com/nerv55/opensourcepos/files/2941255/databas1_ospo13.zip)

**Comment by nerv55** [comment]
ok, this is my mail leonardo.a.salazar@gmail.com  compress copy of your database and send me through wetransfer

**Comment by nerv55** [comment]
ok, let me work on this I will reply you as soon as I finish

**Comment by nerv55** [comment]
Ok, I have prototype ready, give me one example of your data to make comparation and see if it works well.

**Comment by data2base** [comment]
Great! So category would be; Woodworks

date range 1/2/2019 - 28/2/2019
![screenshot_1](https://user-images.githubusercontent.com/37272312/54044949-ec9d8b80-41d8-11e9-9d6e-6020b1617957.png)

**Comment by nerv55** [comment]
The only diference is Stock O/B tell how you get it

![rep](https://user-images.githubusercontent.com/26050096/54047018-ef31be00-41a3-11e9-9d3b-850a4126b780.png)

**Comment by data2base** [comment]
We so not need opening balance. 
This is from an excel spreadsheet. 

We know what is the closing balance.
Can attach the previous month information is this case?

**Comment by data2base** [comment]
Can we add last column payment due. As this will be stock sold x cost price with a total column at the end of each column.

**Comment by nerv55** [comment]
30 days before the initial date (01-02-2019) the entrys are

![rep](https://user-images.githubusercontent.com/26050096/54048205-1c33a000-41a7-11e9-952c-e5c2554f991f.png)

so tell me, from where do you get your initial Stock

**Comment by nerv55** [comment]
Like this?
![rep](https://user-images.githubusercontent.com/26050096/54048478-ed69f980-41a7-11e9-9b99-d67b0895b8d0.png)

**Comment by data2base** [comment]
yes that's great, stock o/b not pulling through correctly. as the other units had stock. payment due is perfect

**Comment by nerv55** [comment]
How do you to get Open Balance Stock?, what is your standard?,

**Comment by data2base** [comment]
closing balance stock of previous month?

**Comment by nerv55** [comment]
yes, closing balance stock of previous month? <---- wich method do you use to get this?

**Comment by data2base** [comment]
no i had no method, was done manually.

**Comment by nerv55** [comment]
yes, I know is manual, but tell me how you get the result? form wich reports you pull the data, that way I can build somethig to put it in the report and do it automatic, or at leat try it.

**Comment by data2base** [comment]
So my process was not system related. 
I took stock received and entered it into the spreadsheet, from there i used the ospos reports to see what sales were processed and stock was calculated from there on. 

Maybe one could use the receiving table and take stock level from there? I have not used it to update stock levels so we can do a test entry.

**Comment by nerv55** [comment]
ok so is like this: (Recived - Sell)+returns = Closing Balance Stock  (interval 30 dias from 01 to end of Month)

**Comment by data2base** [comment]
Yes lets try

**Comment by data2base** [comment]
two types of returns, sale return + "receiving" return

**Comment by nerv55** [comment]
ok, updated formular (Recived + Returns) - (Sells+Reciving Returns) = Closing Balance Stock (interval 30 dias from 01 to end of Month)

**Comment by nerv55** [comment]
Well in your data base you don't have any Recived document form current year. at least the example that you send me does not have

**Comment by data2base** [comment]
No it does not. Ill manually make stock 0 and bring in stock through receivings.

**Comment by nerv55** [comment]
Here is the Query.

SELECT 
ospos3.ospos_items.name,
ifnull((SELECT ifnull(sum(trans_inventory),0) as OB FROM ospos3.ospos_inventory where ospos3.ospos_inventory.trans_items=ospos3.ospos_items.item_id
 and  trans_comment LIKE 'POS%' 
 or  trans_comment LIKE 'RECV%' 
 and  month(ospos_inventory.trans_date) =  month('2019-02-01') -1
 and  year(ospos_inventory.trans_date) = year('2019-02-01')
 group by trans_items),0)  as Stock_Open_Balance,
 ifnull((SELECT ifnull(sum(trans_inventory),0) as OB FROM ospos3.ospos_inventory where ospos3.ospos_inventory.trans_items=ospos3.ospos_items.item_id
 and  trans_comment LIKE 'RECV%' 
 and  month(ospos_inventory.trans_date) =  month('2019-02-01') 
 and  year(ospos_inventory.trans_date) = year('2019-02-01')
 group by trans_items),0)  as New_Stock,
ospos3.ospos_items.cost_price, 
ospos3.ospos_items.unit_price,
ospos3.ospos_stock_locations.location_name,
ifnull((SELECT ifnull((trans_inventory),0)*-1 as OB FROM ospos3.ospos_inventory where ospos3.ospos_inventory.trans_items=ospos3.ospos_items.item_id
 and  trans_comment LIKE 'POS%'   
 and  month(ospos_inventory.trans_date) =  month('2019-02-01') 
 and  year(ospos_inventory.trans_date) = year('2019-02-01')
  group by trans_items),0) as SoldUnits,
ospos3.ospos_item_quantities.quantity as Current_Stock,
(ospos3.ospos_items.cost_price * ospos3.ospos_item_quantities.quantity) AS Current_inventory_Value,
 ((ifnull((SELECT ifnull((trans_inventory),0)*-1 as OB FROM ospos3.ospos_inventory where ospos3.ospos_inventory.trans_items=ospos3.ospos_items.item_id
 and  trans_comment LIKE 'POS%'   
 and  month(ospos_inventory.trans_date) =  month('2019-02-01') 
 and  year(ospos_inventory.trans_date) = year('2019-02-01')
 
 group by trans_items),0))* ospos3.ospos_items.cost_price) as Payment_Due

FROM ospos3.ospos_items
join ospos3.ospos_item_quantities  on ospos3.ospos_items.item_id = ospos3.ospos_item_quantities.item_id
join ospos3.ospos_stock_locations  on ospos3.ospos_item_quantities.location_id = ospos3.ospos_stock_locations.location_id
and ospos3.ospos_items.deleted = 0 
and ospos3.ospos_items.stock_type = 0
and ospos3.ospos_stock_locations.deleted = 0
and ospos3.ospos_items.category = 'Woodworks **Cons'

you can take it from here and make adjustments.

**Comment by data2base** [comment]
Wow thanks so much! Ill test and let you know.

**Comment by data2base** [comment]
Hi! Getting this error. 
![Screenshot_2](https://user-images.githubusercontent.com/37272312/54086547-fa771c00-4352-11e9-97ea-e2ef60dc5379.png)

**Comment by nerv55** [comment]
change ospos3 for the name of your database

**Comment by data2base** [comment]
Hi! Finally building the reports into a system we are developing. Can you assist with a couple of questions?
I can send you my current db, I deleted all items and brought them in via receivings. but not I'm not getting any data in return.
